version: '3.4'
services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
        image: localstack/localstack
        hostname: localstack
        ports:
          - "53:53"
          - "443:443"
          - "4566:4566"
          - "4571:4571"
        environment:
        - SERVICES=${SERVICES}
        - DEBUG=1
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOST_TMP_FOLDER=${TMPDIR}
        - HOSTNAME_EXTERNAL=localstack
        volumes:
        - ./data:/tmp/localstack
        - "/var/run/docker.sock:/var/run/docker.sock"

networks:
    default:
        name: localstack