version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '53:53'
      - '53:53/udp'
      - '443:443'
      - '4510-4520:4510-4520'
      - '4566-4620:4566-4620'
    environment:
      - SERVICE=sqs,rds,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'